### ISSUE TITLE
Implement all parameters for HUDManager.DisplayTip

### ISSUE THREAD

**Issue by Sombody101** [steven4547466/LC-API#18]
Can all of the parameters for `HUDManager.DisplayTip` be implemented to `GameTip`? Overload methods where necessary.

The `GameTip` class only uses two of the parameters (header and body), but there are 5 in total.

```cs
string headerText
string bodyText
bool isWarning = false
bool useSave = false
string prefsKey = "LC_Tip1"
```

This would allow us to give proper user warnings for something like commands, preventing them from *having* to open the terminal output.

**Comment by steven4547466** [comment]
`GameTip` will be deprecated soon for `Player.ShowTip` and `Player.QueueTip` I will ensure these are available!

**Comment by steven4547466** [comment]
See commit d36951f94c1e4214e68a8df00ce4b70fe0508cab
