### ISSUE TITLE
Error that not always occur

### ISSUE THREAD

**Issue by ustaalon** [steven4547466/LC-API#26]
**Given** Player opens new game (save file)
**When** Player opens a new game
**Then** No errors should occur

sometimes it happens and sometimes it's not

[Error  : Unity Log] ArgumentException: An item with the same key has already been added. Key: Player (GameNetcodeStuff.PlayerControllerB)
Stack trace:
System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) (at <787acc3c9a4c471ba7d971300105af24>:0)
System.Collections.Generic.Dictionary`2[TKey,TValue].Add (TKey key, TValue value) (at <787acc3c9a4c471ba7d971300105af24>:0)
LC_API.GameInterfaceAPI.Features.Player.Start () (at <d7b72b80524942c3990d40ef2c6b2e5a>:0)

![image](https://github.com/steven4547466/LC-API/assets/19238320/7925e795-744e-4b31-ba56-6ab2c55a7c75)

**Comment by steven4547466** [comment]
Will look into this.

**Comment by steven4547466** [comment]
Should be fixed in 3.4.0
