### ISSUE TITLE
Invincible

### ISSUE THREAD

**Issue by MaesterEnzo** [steven4547466/LC-API#30]
Update 3.4.0 made player Invincible to everything. Not sure if this is host only or whole lobby, but definitely during a solo host play you are unable to die at all.

**Comment by ShadowFlame365** [comment]
Can confirm, downgrading to 3.3.2 resolves the issue and allows players to be damaged again.

**Comment by m0bz73r** [comment]
Having the same issue. Downgrading also fixed the issue.

**Comment by AdamKissee** [comment]
Now I can finally meet quota.

**Comment by Krovik7** [comment]
Can also confirm, was in a game where 3 of us updated and 3 of us hadn't (including the host), updated people couldn't die

**Comment by decafhotchocolate** [comment]
Can confirm the same issue

**Comment by Schwar7z** [comment]
_I just want to die_

**Comment by osxdude** [comment]
Can confirm, downgrading to 3.3.2 fixes.

**Comment by steven4547466** [comment]
Fixed in 3.4.1.

If an issue like this comes up I have a much faster response rate in the LC modding discord.
