### ISSUE TITLE
After picking up the item, there will be two icons

### ISSUE THREAD

**Issue by smilepeak** [steven4547466/LC-API#32]
After updating version 3.4.3, the picked up items will become two, and the discarded item icon will not disappear.
Restore normal after deleting mods.
I hope this log file is helpful to you, the code should be at the end.
[log.txt](https://github.com/steven4547466/LC-API/files/13944898/log.txt)

![111](https://github.com/steven4547466/LC-API/assets/73094803/c14f2898-c113-46b7-9a63-03beb0c52639)

**Comment by steven4547466** [comment]
https://github.com/steven4547466/LC-API/assets/23726534/0b4d13be-11a8-43cf-9632-1f52c42a57f4

Can't seem to recreate it, is it only shovels?

**Comment by smilepeak** [comment]
Any item will behave like this. I thought it was in conflict with other mods, but I deleted all other mods
This video is too big, so I uploaded it to Google Cloud Drive.
https://drive.google.com/file/d/1m-Rp3n_5q5t5LWLBkH0QZ9cyGitBcmGg/view?usp=sharing

**Comment by smilepeak** [comment]
I seem to have identified the problem, which occurs when this option is set to true.
![123](https://github.com/steven4547466/LC-API/assets/73094803/12c69096-05d6-4c06-bd90-60499569d65f)

I hope this log file is helpful to you.
[LOG.txt](https://github.com/steven4547466/LC-API/files/13945827/LOG.txt)

**Comment by steven4547466** [comment]
Fixed in https://github.com/steven4547466/LC-API/releases/tag/v3.4.4
