### ISSUE TITLE
Teammate dead, still standing

### ISSUE THREAD

**Issue by smilepeak** [steven4547466/LC-API#33]
Vanilla Compatibility = true
When this option is set to true, after a teammate dies, the body will stand and the teammate's voice can be heard
![111](https://github.com/steven4547466/LC-API/assets/73094803/095356e0-f11b-42dc-bb0a-5a749ae040c7)

**Comment by BradBergstrom** [comment]
Experiencing this as well. When someone dies, the game treats it as two separate people dying. I can tell this, because when I die, it shows that there are 2 people who need to vote to leave, but actually I'm the only one who died. It also won't let people spectate. The results screen is also bugged, usually showing none, or just 1 death. The only mods I have are BiggerCompany, and BepInEx

**Comment by steven4547466** [comment]
Can you send logs?

**Comment by smilepeak** [comment]
I hope this log is helpful to you
Reproducing it is actually very simple, just find a place to jump down
The body will be in a standing state
[log.txt](https://github.com/steven4547466/LC-API/files/13974465/log.txt)

https://github.com/steven4547466/LC-API/assets/73094803/3bdf8d5c-f714-4727-820c-6a0a0ed95499

**Comment by smilepeak** [comment]
This video is under normal circumstances



https://github.com/steven4547466/LC-API/assets/73094803/661c64da-4d43-4fb7-a858-c104143dba73

**Comment by smilepeak** [comment]
And I also discovered another bug, when Vanilla Compatibility is true, jumping off the boat does not result in falling to death
[LOG2.txt](https://github.com/steven4547466/LC-API/files/13974562/LOG2.txt)

https://github.com/steven4547466/LC-API/assets/73094803/14e04a9e-1748-4ed5-9ea9-453f6c0f9980

**Comment by BradBergstrom** [comment]
I think that is the issue, I did not experience this bug until vanilla compatibility was turned on.

**Comment by steven4547466** [comment]
Should be fixed in [v3.4.5](https://github.com/steven4547466/LC-API/releases/tag/v3.4.5)
